name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-setuptools python3-pip openjdk-17-jdk unzip

    - name: Install buildozer
      run: pip3 install buildozer

    - name: Build with buildozer
      run: buildozer android debug
