name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: schniz/buildozer-action@v4
        id: buildozer
        with:
          args: android debug
